version: "3.7"

services:
  application:
    build: .
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    volumes:
      - ./:/app
    env_file:
      - api.env
  redis:
    image: redis
    container_name: redis
    hostname: "redis"
    ports:
      - 49155:6379

  postgresql:
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    image: postgres:15.0
    volumes:
      - postgresql-data:/var/lib/postgres
    env_file:
      - api.env


volumes:
  postgresql-data:
