jwt:
  secret: ${JWT_SECRET}

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: ${FACEBOOK_CLIENT_ID}
            clientSecret: ${FACEBOOK_SECRET}

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    database: postgresql

  datasource:
    platform: postgres
    url: "jdbc:postgresql://postgresql:5432/${POSTGRES_DB}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true